### ISSUE TITLE
Another directory issue

### ISSUE THREAD

**Issue by keflavich** [GalagaBits/JWST-FGS-Spelunker#10]
Ran into this problem trying the latest version:
```
Traceback (most recent call last):
  File "<ipython-input-1-460cda62bfbc>", line 3, in <module>
    spk = spelunker.load(pid=2221)
  File "/home/adam/anaconda3/envs/python3.9/lib/python3.9/site-packages/spelunker/spelunker.py", line 86, in __init__
    self.download(pid, obs_num=obs_num, visit=visit, visit_group=visit_group, parallel_sequnence_id=parallel_sequnence_id,
  File "/home/adam/anaconda3/envs/python3.9/lib/python3.9/site-packages/spelunker/spelunker.py", line 384, in download
    reformed_directory = np.char.add(np.char.add(fg_table['sliced_directory'], f_slash), fg_table['filenames'])
  File "<__array_function__ internals>", line 180, in add
  File "/home/adam/anaconda3/envs/python3.9/lib/python3.9/site-packages/numpy/core/defchararray.py", line 310, in add
    return _vec_string(arr1, (dtype, out_size), '__add__', (arr2,))
TypeError: string operation on non-string array
```

you should probably use `os.path.join` rather than `np.char.add` to join path components

**Comment by GalagaBits** [comment]
For this issue, the program id `2221` has exclusive rights, so it won't be able to download the data publicly. The error occurred because there is no filename downloaded from MAST, so there is no string available for the filename it is trying to join together. However, there is an new fix coming that will allow you to input your own private data with MAST API.

**Comment by GalagaBits** [comment]
The lasted release of `Spelunker` has been launched. After upgrading Spelunker `pip install --upgrade spelunker`, try inputing your MAST API token associated with your Program ID into the `load` method. So for example, `spk = spelunker.load(pid=2221, token='your_token')`. If it works, let me know!

**Comment by nespinoza** [comment]
Closing issues as this has been fixed.
